(in-package #:cl-mmix)

;;; S-expression assembler. Emits the same opcode bytes as mmixal:
;;; forward and backward branches, JMP/JMPB, GETA/GETAB.
;;;
;;;   (program
;;;     (:org #x100)
;;;     (label :start)
;;;     (setl $1 10)
;;;     (bz $1 :done)
;;;     (jmp :start)
;;;     (label :done)
;;;     (trap 0 0 0)
;;;     (:org #x2000000000000000)
;;;     (:zstring "hi"))
;;;
;;; Each :org starts a segment written at that address. The VM's PC is
;;; the first origin. Registers are $3 or 3. Branch, JMP, GETA, and PUSHJ
;;; targets are labels; the forward or backward opcode is chosen from the
;;; sign of the displacement.

(defparameter +branch-forward+
  '((:bn . #x40) (:bnb . #x40)
    (:bz . #x42) (:bzb . #x42)
    (:bp . #x44) (:bpb . #x44)
    (:bod . #x46) (:bodb . #x46)
    (:bnn . #x48) (:bnnb . #x48)
    (:bnz . #x4A) (:bnzb . #x4A)
    (:bnp . #x4C) (:bnpb . #x4C)
    (:bev . #x4E) (:bevb . #x4E)
    (:pbn . #x50) (:pbnb . #x50)
    (:pbz . #x52) (:pbzb . #x52)
    (:pbp . #x54) (:pbpb . #x54)
    (:pbod . #x56) (:pbodb . #x56)
    (:pbnn . #x58) (:pbnnb . #x58)
    (:pbnz . #x5A) (:pbnzb . #x5A)
    (:pbnp . #x5C) (:pbnpb . #x5C)
    (:pbev . #x5E) (:pbevb . #x5E)
    (:pushj . #xF2) (:pushjb . #xF2)
    (:geta . #xF4) (:getab . #xF4))
  "Keyword → even opcode. The backward form is that opcode plus one.")

(defun parse-reg (r)
  (cond
    ((integerp r)
     (unless (<= 0 r 255) (error "Register out of range: ~S" r))
     r)
    ((and (symbolp r)
          (let ((n (symbol-name r)))
            (and (plusp (length n))
                 (char= (char n 0) #\$)
                 (every #'digit-char-p (subseq n 1)))))
     (parse-integer (subseq (symbol-name r) 1)))
    (t (error "Bad register: ~S" r))))

(defun parse-special (s)
  (cond
    ((integerp s)
     (unless (<= 0 s 31) (error "Special register out of range: ~S" s))
     s)
    ((symbolp s)
     (let* ((n (string-upcase (symbol-name s)))
            (n (if (and (> (length n) 1) (char= (char n 0) #\R))
                   (subseq n 1)
                   n)))
       (or (loop for i below 32
                 when (string= n (aref +special-names+ i))
                   return i)
           (error "Unknown special register: ~S" s))))
    (t (error "Bad special register: ~S" s))))

(defun form-key (name)
  (op-name-key name))

(defun string-byte-list (s null-terminate)
  (let ((bytes (map 'list #'char-code s)))
    (dolist (b bytes)
      (unless (<= 0 b 255)
        (error "String byte does not fit in 8 bits: ~S" b)))
    (if null-terminate (append bytes '(0)) bytes)))

(defun form-nbytes (form)
  (if (not (consp form))
      0
      (case (form-key (first form))
        ((:org :label) 0)
        (:byte (length (rest form)))
        (:wyde (* 2 (length (rest form))))
        (:tetra (* 4 (length (rest form))))
        ((:octa :word) (* 8 (length (rest form))))
        (:string (length (string-byte-list (second form) nil)))
        (:zstring (length (string-byte-list (second form) t)))
        (t 4))))

(defun collect-labels (forms origin)
  (let ((labels (make-hash-table :test 'equal))
        (addr origin))
    (dolist (form forms)
      (cond
        ((and (consp form) (eq (form-key (first form)) :org))
         (setf addr (second form)))
        ((and (consp form) (eq (form-key (first form)) :label))
         (setf (gethash (second form) labels) addr))
        ((consp form)
         (incf addr (form-nbytes form)))))
    labels))

(defun label-delta (labels pc target)
  (let ((addr (gethash target labels)))
    (unless addr (error "Undefined label: ~S" target))
    (let ((diff (- addr pc)))
      (unless (zerop (mod diff 4))
        (error "Label ~S is not a multiple of 4 bytes from #x~X" target pc))
      (truncate diff 4))))

(defun resolve-abs (imm labels)
  (cond
    ((integerp imm) imm)
    ((or (symbolp imm) (stringp imm))
     (or (gethash imm labels)
         (error "Undefined label: ~S" imm)))
    (t (error "Bad immediate: ~S" imm))))

(defun bytes4 (op x y z)
  (list (u8 op) (u8 x) (u8 y) (u8 z)))

(defun split-field (value bits)
  (let ((mask (1- (ash 1 bits))))
    (values (ldb (byte 8 (- bits 8)) (logand value mask))
            (if (> bits 16)
                (ldb (byte 8 (- bits 16)) (logand value mask))
                0)
            (ldb (byte 8 0) (logand value mask)))))

(defun encode-relative (forward-byte delta bits)
  (let ((min (- (ash 1 bits)))
        (max (1- (ash 1 bits))))
    (unless (<= min delta max)
      (error "Relative displacement ~D does not fit in ~D bits" delta bits))
    (if (minusp delta)
        (values (1+ forward-byte) (logand (+ delta (ash 1 bits)) (1- (ash 1 bits))))
        (values forward-byte delta))))

(defun emit-data-bytes (form)
  (case (form-key (first form))
    (:byte (mapcar #'u8 (rest form)))
    (:wyde
     (loop for w in (rest form)
           for v = (u16 w)
           append (list (ldb (byte 8 8) v) (ldb (byte 8 0) v))))
    (:tetra
     (loop for w in (rest form)
           for v = (u32 w)
           append (list (ldb (byte 8 24) v) (ldb (byte 8 16) v)
                        (ldb (byte 8 8) v) (ldb (byte 8 0) v))))
    ((:octa :word)
     (loop for w in (rest form)
           nconc (let ((v (u64 w)))
                   (loop for shift from 56 downto 0 by 8
                         collect (ldb (byte 8 shift) v)))))
    (:string (string-byte-list (second form) nil))
    (:zstring (string-byte-list (second form) t))
    (t nil)))

(defun alias-op (key)
  "Single-instruction MMIXAL spellings. LDA is ADDU, not a four-instruction expansion."
  (case key
    (:lda :addu)
    (:ldai :addui)
    (t key)))

(defun immediate-mnemonic-p (key)
  (let ((s (symbol-name key)))
    (and (> (length s) 1)
         (char= (char s (1- (length s))) #\I)
         (not (member key '(:puti :negi :negui))))))

(defun encode-form (form labels pc)
  (let ((key (alias-op (form-key (first form)))))
    (cond
      ((member key '(:org :label)) nil)
      ((member key '(:byte :wyde :tetra :octa :word :string :zstring))
       (emit-data-bytes form))
      ((assoc key +branch-forward+)
       (let* ((x (parse-reg (second form)))
              (delta (label-delta labels pc (third form)))
              (forward (cdr (assoc key +branch-forward+))))
         (multiple-value-bind (op disp) (encode-relative forward delta 16)
           (bytes4 op x (ldb (byte 8 8) disp) (ldb (byte 8 0) disp)))))
      ((member key '(:jmp :jmpb))
       (multiple-value-bind (op disp)
           (encode-relative #xF0 (label-delta labels pc (second form)) 24)
         (bytes4 op
                 (ldb (byte 8 16) disp)
                 (ldb (byte 8 8) disp)
                 (ldb (byte 8 0) disp))))
      ((eq key :trap)
       (bytes4 (op-byte :trap)
               (u8 (or (second form) 0))
               (u8 (or (third form) 0))
               (u8 (or (fourth form) 0))))
      ((eq key :trip)
       (bytes4 (op-byte :trip)
               (u8 (or (second form) 0))
               (u8 (or (third form) 0))
               (u8 (or (fourth form) 0))))
      ((eq key :pop)
       (bytes4 (op-byte :pop)
               (u8 (second form))
               (ldb (byte 8 8) (u16 (or (third form) 0)))
               (ldb (byte 8 0) (u16 (or (third form) 0)))))
      ((eq key :get)
       (bytes4 (op-byte :get) (parse-reg (second form)) 0
               (parse-special (third form))))
      ((eq key :put)
       (bytes4 (op-byte :put) (parse-special (second form)) 0
               (parse-reg (third form))))
      ((eq key :puti)
       (bytes4 (op-byte :puti) (parse-special (second form)) 0
               (u8 (third form))))
      ((member key '(:neg :negu :negi :negui))
       (bytes4 (op-byte key)
               (parse-reg (second form))
               (u8 (third form))
               (if (member key '(:negi :negui))
                   (u8 (fourth form))
                   (parse-reg (fourth form)))))
      ((eq key :set)
       (bytes4 (op-byte :ori) (parse-reg (second form))
               (parse-reg (third form)) 0))
      ((member key '(:swym :save :unsave))
       (let ((xyz (logand (or (second form) 0) #xffffff)))
         (bytes4 (op-byte key)
                 (ldb (byte 8 16) xyz)
                 (ldb (byte 8 8) xyz)
                 (ldb (byte 8 0) xyz))))
      ((eq key :sync)
       (let ((xyz (logand (or (second form) 0) #xffffff)))
         (bytes4 (op-byte :sync)
                 (ldb (byte 8 16) xyz)
                 (ldb (byte 8 8) xyz)
                 (ldb (byte 8 0) xyz))))
      ((eq key :resume)
       (let ((xyz (logand (or (second form) 0) #xffffff)))
         (bytes4 (op-byte :resume)
                 (ldb (byte 8 16) xyz)
                 (ldb (byte 8 8) xyz)
                 (ldb (byte 8 0) xyz))))
      ((member key '(:seth :setmh :setml :setl
                      :inch :incmh :incml :incl
                      :orh :ormh :orml :orl
                      :andnh :andnmh :andnml :andnl))
       (let ((raw (resolve-abs (third form) labels)))
         (unless (<= 0 raw #xFFFF)
           (error "Wyde immediate does not fit: ~S" (third form)))
         (bytes4 (op-byte key) (parse-reg (second form))
                 (ldb (byte 8 8) raw) (ldb (byte 8 0) raw))))
      ((immediate-mnemonic-p key)
       (let ((imm (resolve-abs (fourth form) labels)))
         (unless (<= 0 imm 255)
           (error "Immediate does not fit in a byte: ~S" (fourth form)))
         (bytes4 (op-byte key)
                 (parse-reg (second form))
                 (parse-reg (third form))
                 imm)))
      (t
       (bytes4 (op-byte key)
               (parse-reg (second form))
               (parse-reg (third form))
               (parse-reg (fourth form)))))))

(defun program-forms (program)
  (if (and (consp program)
           (symbolp (first program))
           (string-equal (symbol-name (first program)) "PROGRAM"))
      (rest program)
      program))

(defun assemble (program &key (origin 0))
  "Assemble PROGRAM.
Returns (values segments origin labels). SEGMENTS is a list of
(address . byte-vector), one per contiguous run between :org directives."
  (let* ((forms (program-forms program))
         (org origin))
    (when (and forms (consp (first forms)) (eq (form-key (caar forms)) :org))
      (setf org (second (first forms))))
    (let ((labels (collect-labels forms org))
          (segments nil)
          (buf nil)
          (start nil)
          (open nil)
          (pc org))
      (labels ((flush ()
                 (when (and open buf)
                   (push (cons start
                               (coerce (nreverse buf)
                                       '(simple-array (unsigned-byte 8) (*))))
                         segments))
                 (setf buf nil open nil)))
        (dolist (form forms)
          (cond
            ((and (consp form) (eq (form-key (first form)) :org))
             (flush)
             (setf pc (second form) start pc open t))
            ((and (consp form) (eq (form-key (first form)) :label))
             nil)
            ((consp form)
             (unless open
               (setf start pc open t))
             (let ((bytes (encode-form form labels pc))
                   (n (form-nbytes form)))
               (unless (= (length bytes) n)
                 (error "Assembler size mismatch for ~S: encoded ~D, declared ~D"
                        form (length bytes) n))
               (dolist (b bytes)
                 (push b buf))
               (incf pc n)))))
        (flush))
      (values (nreverse segments) org labels))))

(defun assemble-into (vm program &key (origin 0))
  "Assemble PROGRAM and write each segment at its own address.
PC becomes the first origin. Labels are stored on the VM."
  (multiple-value-bind (segments org labels) (assemble program :origin origin)
    (dolist (seg segments)
      (loop for b across (cdr seg)
            for i from 0
            do (mem-set-u8 vm (+ (car seg) i) b)))
    (setf (vm-pc vm) (u64 org)
          (vm-halted vm) nil
          (vm-cycles vm) 0
          (vm-mems vm) 0
          (vm-fault vm) nil
          (vm-labels vm) labels)
    (values vm org labels)))

(defun load-program (vm bytes &key (origin 0))
  "Load a byte vector into VM at ORIGIN and set PC."
  (loop for i from 0 below (length bytes)
        do (mem-set-u8 vm (+ origin i) (aref bytes i)))
  (setf (vm-pc vm) (u64 origin)
        (vm-halted vm) nil
        (vm-cycles vm) 0)
  vm)
