(in-package #:cl-mmix)

;;; Full MMIX opcode map (Knuth, mmop.html). Execution of floating-point
;;; and of SAVE/UNSAVE is deferred; the names are still known to the decoder.

(defvar *op-byte* (make-hash-table :test 'eq))
(defvar *op-name* (make-array 256 :initial-element :unknown))

(defun register-op (byte name)
  (setf (aref *op-name* byte) name)
  (setf (gethash name *op-byte*) byte)
  name)

(defun register-pair (byte name)
  "Register BYTE as NAME and BYTE+1 as the immediate form NAMEI."
  (register-op byte name)
  (register-op (1+ byte)
               (intern (concatenate 'string (symbol-name name) "I") :keyword)))

(defun register-branch (byte name)
  "Register BYTE as NAME and BYTE+1 as the backward form NAMEB."
  (register-op byte name)
  (register-op (1+ byte)
               (intern (concatenate 'string (symbol-name name) "B") :keyword)))

(register-op #x00 :trap)
(register-op #x01 :fcmp)
(register-op #x02 :fun)
(register-op #x03 :feql)
(register-op #x04 :fadd)
(register-op #x05 :fix)
(register-op #x06 :fsub)
(register-op #x07 :fixu)
(register-pair #x08 :flot)
(register-pair #x0A :flotu)
(register-pair #x0C :sflot)
(register-pair #x0E :sflotu)
(register-op #x10 :fmul)
(register-op #x11 :fcmpe)
(register-op #x12 :fune)
(register-op #x13 :feqle)
(register-op #x14 :fdiv)
(register-op #x15 :fsqrt)
(register-op #x16 :frem)
(register-op #x17 :fint)

(register-pair #x18 :mul)
(register-pair #x1A :mulu)
(register-pair #x1C :div)
(register-pair #x1E :divu)
(register-pair #x20 :add)
(register-pair #x22 :addu)
(register-pair #x24 :sub)
(register-pair #x26 :subu)
(register-pair #x28 :2addu)
(register-pair #x2A :4addu)
(register-pair #x2C :8addu)
(register-pair #x2E :16addu)
(register-pair #x30 :cmp)
(register-pair #x32 :cmpu)
(register-pair #x34 :neg)
(register-pair #x36 :negu)
(register-pair #x38 :sl)
(register-pair #x3A :slu)
(register-pair #x3C :sr)
(register-pair #x3E :sru)

(register-branch #x40 :bn)
(register-branch #x42 :bz)
(register-branch #x44 :bp)
(register-branch #x46 :bod)
(register-branch #x48 :bnn)
(register-branch #x4A :bnz)
(register-branch #x4C :bnp)
(register-branch #x4E :bev)
(register-branch #x50 :pbn)
(register-branch #x52 :pbz)
(register-branch #x54 :pbp)
(register-branch #x56 :pbod)
(register-branch #x58 :pbnn)
(register-branch #x5A :pbnz)
(register-branch #x5C :pbnp)
(register-branch #x5E :pbev)

(register-pair #x60 :csn)
(register-pair #x62 :csz)
(register-pair #x64 :csp)
(register-pair #x66 :csod)
(register-pair #x68 :csnn)
(register-pair #x6A :csnz)
(register-pair #x6C :csnp)
(register-pair #x6E :csev)
(register-pair #x70 :zsn)
(register-pair #x72 :zsz)
(register-pair #x74 :zsp)
(register-pair #x76 :zsod)
(register-pair #x78 :zsnn)
(register-pair #x7A :zsnz)
(register-pair #x7C :zsnp)
(register-pair #x7E :zsev)

(register-pair #x80 :ldb)
(register-pair #x82 :ldbu)
(register-pair #x84 :ldw)
(register-pair #x86 :ldwu)
(register-pair #x88 :ldt)
(register-pair #x8A :ldtu)
(register-pair #x8C :ldo)
(register-pair #x8E :ldou)
(register-pair #x90 :ldsf)
(register-pair #x92 :ldht)
(register-pair #x94 :cswap)
(register-pair #x96 :ldunc)
(register-pair #x98 :ldvts)
(register-pair #x9A :preld)
(register-pair #x9C :prego)
(register-pair #x9E :go)
(register-pair #xA0 :stb)
(register-pair #xA2 :stbu)
(register-pair #xA4 :stw)
(register-pair #xA6 :stwu)
(register-pair #xA8 :stt)
(register-pair #xAA :sttu)
(register-pair #xAC :sto)
(register-pair #xAE :stou)
(register-pair #xB0 :stsf)
(register-pair #xB2 :stht)
(register-pair #xB4 :stco)
(register-pair #xB6 :stunc)
(register-pair #xB8 :syncd)
(register-pair #xBA :prest)
(register-pair #xBC :syncid)
(register-pair #xBE :pushgo)

(register-pair #xC0 :or)
(register-pair #xC2 :orn)
(register-pair #xC4 :nor)
(register-pair #xC6 :xor)
(register-pair #xC8 :and)
(register-pair #xCA :andn)
(register-pair #xCC :nand)
(register-pair #xCE :nxor)
(register-pair #xD0 :bdif)
(register-pair #xD2 :wdif)
(register-pair #xD4 :tdif)
(register-pair #xD6 :odif)
(register-pair #xD8 :mux)
(register-pair #xDA :sadd)
(register-pair #xDC :mor)
(register-pair #xDE :mxor)

(register-op #xE0 :seth)
(register-op #xE1 :setmh)
(register-op #xE2 :setml)
(register-op #xE3 :setl)
(register-op #xE4 :inch)
(register-op #xE5 :incmh)
(register-op #xE6 :incml)
(register-op #xE7 :incl)
(register-op #xE8 :orh)
(register-op #xE9 :ormh)
(register-op #xEA :orml)
(register-op #xEB :orl)
(register-op #xEC :andnh)
(register-op #xED :andnmh)
(register-op #xEE :andnml)
(register-op #xEF :andnl)

(register-branch #xF0 :jmp)
(register-branch #xF2 :pushj)
(register-branch #xF4 :geta)
(register-op #xF6 :put)
(register-op #xF7 :puti)
(register-op #xF8 :pop)
(register-op #xF9 :resume)
(register-op #xFA :save)
(register-op #xFB :unsave)
(register-op #xFC :sync)
(register-op #xFD :swym)
(register-op #xFE :get)
(register-op #xFF :trip)

(defparameter +op+
  (loop for byte below 256
        for name = (aref *op-name* byte)
        unless (eq name :unknown)
          collect (cons name byte))
  "Alist of opcode keywords → byte values.")

(defun op-name-key (name)
  "Normalize an opcode designator to a keyword."
  (cond
    ((keywordp name) name)
    ((symbolp name) (intern (symbol-name name) :keyword))
    ((stringp name) (intern (string-upcase name) :keyword))
    (t (error "Bad opcode designator: ~S" name))))

(defun op-byte (name)
  (let ((key (op-name-key name)))
    (or (gethash key *op-byte*)
        (error "Unknown opcode name: ~S" name))))

(defun op-name (byte)
  (aref *op-name* (u8 byte)))

(defstruct (instruction (:conc-name inst-))
  (op 0 :type (unsigned-byte 8))
  (x  0 :type (unsigned-byte 8))
  (y  0 :type (unsigned-byte 8))
  (z  0 :type (unsigned-byte 8))
  (raw 0 :type (unsigned-byte 32)))

(defun decode (word)
  "Decode a 32-bit big-endian instruction word into an INSTRUCTION."
  (let ((w (u32 word)))
    (make-instruction
     :op  (ldb (byte 8 24) w)
     :x   (ldb (byte 8 16) w)
     :y   (ldb (byte 8 8) w)
     :z   (ldb (byte 8 0) w)
     :raw w)))

(defun encode (op x y z)
  "Encode OP X Y Z into a 32-bit instruction word."
  (logior (ash (u8 (if (symbolp op) (op-byte op) op)) 24)
          (ash (u8 x) 16)
          (ash (u8 y) 8)
          (u8 z)))

(defun inst-yz (inst)
  (logior (ash (inst-y inst) 8) (inst-z inst)))

(defun inst-xyz (inst)
  (logior (ash (inst-x inst) 16)
          (ash (inst-y inst) 8)
          (inst-z inst)))

(defun fetch (vm)
  "Fetch the tetrabyte at PC, ignoring the low two bits. Does not advance PC."
  (mem-ref-u32 vm (logand (vm-pc vm) (lognot 3)) :internal t))

(defun relative-disp (field bits backward)
  (if backward (- field (ash 1 bits)) field))

(defun disassemble-at (vm &optional (addr (vm-pc vm)))
  "Return a human-readable string for the instruction at ADDR."
  (let* ((addr (logand (u64 addr) (lognot 3)))
         (word (mem-ref-u32 vm addr :internal t))
         (inst (decode word))
         (op (inst-op inst))
         (name (op-name op))
         (x (inst-x inst))
         (y (inst-y inst))
         (z (inst-z inst))
         (yz (inst-yz inst))
         (xyz (inst-xyz inst)))
    (cond
      ((eq name :unknown)
       (format nil "??? #~8,'0X" word))
      ((<= #xE0 op #xEF)
       (format nil "~A $~D,#~4,'0X" name x yz))
      ((or (= op #xF0) (= op #xF1))
       (format nil "~A #x~X"
               name
               (u64 (+ addr (* 4 (relative-disp xyz 24 (= op #xF1)))))))
      ((or (= op #xF2) (= op #xF3) (= op #xF4) (= op #xF5)
           (<= #x40 op #x5F))
       (format nil "~A $~D,#x~X"
               name x
               (u64 (+ addr (* 4 (relative-disp yz 16 (oddp op)))))))
      ((= op #xF6)
       (format nil "PUT ~A,$~D" (special-name x) z))
      ((= op #xF7)
       (format nil "PUTI ~A,~D" (special-name x) z))
      ((= op #xF8)
       (format nil "POP ~D,~D" x yz))
      ((= op #xFE)
       (format nil "GET $~D,~A" x (special-name z)))
      ((= op #x00)
       (format nil "TRAP ~D,~D,~D" x y z))
      ((= op #xFF)
       (format nil "TRIP ~D,~D,~D" x y z))
      ((member op '(#xF9 #xFA #xFB #xFC #xFD))
       (format nil "~A ~D" name xyz))
      ((oddp op)
       (format nil "~A $~D,$~D,~D" name x y z))
      (t
       (format nil "~A $~D,$~D,$~D" name x y z)))))
