(in-package #:cl-mmix)

;;; MMIXAL subset (Knuth, mmixal.w). Lines are label, opcode, operand,
;;; separated by blanks. A line whose first character is not a letter,
;;; digit, or blank is a comment, so % and // comments work. Inside an
;;; operand, % is remainder. The rest of a line after the operand is ignored.
;;;
;;; Symbols are fully qualified with the current prefix, which starts as ":".
;;; GREG counts down from 255 and never assigns $255. rG is that counter.
;;; Instruction bytes come from encode-form / encode-relative / emit-data-bytes.

(defvar *mmixal-file* "input.mms")
(defvar *mmixal-line* 1)

(defun mmixal-error (fmt &rest args)
  (error "MMIXAL ~A:~D: ~A"
         *mmixal-file* *mmixal-line*
         (apply #'format nil fmt args)))

(defstruct mmixal-image
  (rg 255 :type unsigned-byte)
  (regs (make-hash-table :test 'equal) :type hash-table)
  (values (make-hash-table :test 'eql) :type hash-table)
  (specs nil :type list)
  (lines (make-hash-table :test 'eql) :type hash-table)
  (symbols nil :type list)
  (bases nil :type list))

(defstruct msym
  name
  kind
  value
  predefined
  redefined)

(defstruct mstmt
  file
  line
  label
  op
  operands
  ;; NIL until the location walk assigns an address. Zero is a real address.
  (addr nil)
  (size 0)
  ;; (index locals-vector local-names) after addresses exist.
  (meta nil))

(defun mmixal-letter-p (c)
  (or (alpha-char-p c)
      (char= c #\:)
      (char= c #\_)
      (> (char-code c) 126)))

(defun mmixal-letter-or-digit-p (c)
  (or (mmixal-letter-p c) (digit-char-p c)))

(defun mmixal-ws-p (c)
  (or (char= c #\Space) (char= c #\Tab)))

(defun predef-octa (hi lo)
  (logior (ash hi 32) lo))

(defun make-predef-table ()
  (let ((table (make-hash-table :test 'equal)))
    (loop for i below 32
          do (setf (gethash (concatenate 'string ":" "r" (aref +special-names+ i))
                            table)
                   (make-msym :name (concatenate 'string ":" "r" (aref +special-names+ i))
                              :kind :abs :value i :predefined t)))
    (loop for (name hi lo) in
          `(("ROUND_CURRENT" 0 0) ("ROUND_OFF" 0 1) ("ROUND_UP" 0 2)
            ("ROUND_DOWN" 0 3) ("ROUND_NEAR" 0 4)
            ("Inf" #x7ff00000 0)
            ("Text_Segment" 0 0)
            ("Data_Segment" #x20000000 0)
            ("Pool_Segment" #x40000000 0)
            ("Stack_Segment" #x60000000 0)
            ("D_BIT" 0 #x80) ("V_BIT" 0 #x40) ("W_BIT" 0 #x20) ("I_BIT" 0 #x10)
            ("O_BIT" 0 #x08) ("U_BIT" 0 #x04) ("Z_BIT" 0 #x02) ("X_BIT" 0 #x01)
            ("D_Handler" 0 #x10) ("V_Handler" 0 #x20) ("W_Handler" 0 #x30)
            ("I_Handler" 0 #x40) ("O_Handler" 0 #x50) ("U_Handler" 0 #x60)
            ("Z_Handler" 0 #x70) ("X_Handler" 0 #x80)
            ("StdIn" 0 0) ("StdOut" 0 1) ("StdErr" 0 2)
            ("TextRead" 0 0) ("TextWrite" 0 1) ("BinaryRead" 0 2)
            ("BinaryWrite" 0 3) ("BinaryReadWrite" 0 4)
            ("Halt" 0 0) ("Fopen" 0 1) ("Fclose" 0 2) ("Fread" 0 3)
            ("Fgets" 0 4) ("Fgetws" 0 5) ("Fwrite" 0 6) ("Fputs" 0 7)
            ("Fputws" 0 8) ("Fseek" 0 9) ("Ftell" 0 10))
          for qname = (concatenate 'string ":" name)
          do (setf (gethash qname table)
                   (make-msym :name qname :kind :abs
                              :value (predef-octa hi lo) :predefined t)))
    table))

(defun qualify-symbol (prefix name)
  (if (and (plusp (length name)) (char= (char name 0) #\:))
      name
      (concatenate 'string prefix name)))

(defun local-label-string-p (s)
  (and (= (length s) 2)
       (digit-char-p (char s 0))
       (find (char-upcase (char s 1)) "HFB")))

(defun comment-at-p (s i)
  (or (char= (char s i) #\%)
      (and (char= (char s i) #\/)
           (< (1+ i) (length s))
           (char= (char s (1+ i)) #\/))))

(defun skip-ws-index (s i)
  (loop while (and (< i (length s)) (mmixal-ws-p (char s i)))
        do (incf i))
  i)

(defun field-end-index (s i)
  (or (position-if #'mmixal-ws-p s :start i) (length s)))

(defun take-operand-text (s start)
  "Operand text runs up to a blank or semicolon outside a quote."
  (let ((i start)
        (chars nil)
        (n (length s)))
    (loop while (< i n)
          for c = (char s i)
          do (cond
               ((char= c #\")
                (push c chars)
                (incf i)
                (loop while (< i n)
                      for d = (char s i)
                      do (push d chars)
                         (incf i)
                         (when (char= d #\") (return))))
               ((char= c #\')
                (push c chars)
                (incf i)
                (when (< i n)
                  (push (char s i) chars)
                  (incf i))
                (when (and (< i n) (char= (char s i) #\'))
                  (push (char s i) chars)
                  (incf i)))
               ((or (mmixal-ws-p c) (char= c #\;))
                (return))
               (t (push c chars)
                  (incf i))))
    (values (coerce (nreverse chars) 'string) i)))

(defun lex-operand (text)
  (let ((i 0)
        (n (length text))
        (toks nil))
    (loop while (< i n)
          for c = (char text i)
          do (cond
               ((mmixal-ws-p c) (incf i))
               ((char= c #\,) (push (list :comma) toks) (incf i))
               ((char= c #\() (push (list :lparen) toks) (incf i))
               ((char= c #\)) (push (list :rparen) toks) (incf i))
               ((char= c #\@) (push (list :at) toks) (incf i))
               ((char= c #\+) (push (list :op :+) toks) (incf i))
               ((char= c #\-) (push (list :op :-) toks) (incf i))
               ((char= c #\*) (push (list :op :*) toks) (incf i))
               ((char= c #\/) (push (list :op :/) toks) (incf i))
               ((char= c #\%) (push (list :op :%) toks) (incf i))
               ((char= c #\&) (push (list :op :&) toks) (incf i))
               ((char= c #\|) (push (list :op :\|) toks) (incf i))
               ((char= c #\^) (push (list :op :^) toks) (incf i))
               ((char= c #\~) (push (list :op :~) toks) (incf i))
               ((and (char= c #\<) (< (1+ i) n) (char= (char text (1+ i)) #\<))
                (push (list :op :<<) toks)
                (incf i 2))
               ((and (char= c #\>) (< (1+ i) n) (char= (char text (1+ i)) #\>))
                (push (list :op :>>) toks)
                (incf i 2))
               ((char= c #\$)
                (incf i)
                (if (and (< i n) (digit-char-p (char text i)))
                    (let ((j i))
                      (loop while (and (< j n) (digit-char-p (char text j)))
                            do (incf j))
                      (push (list :reg (parse-integer text :start i :end j)) toks)
                      (setf i j))
                    (push (list :op :$) toks)))
               ((char= c #\#)
                (incf i)
                (let ((j i))
                  (loop while (and (< j n) (digit-char-p (char text j) 16))
                        do (incf j))
                  (when (= j i) (mmixal-error "bad hexadecimal constant"))
                  (push (list :int (parse-integer text :start i :end j :radix 16)) toks)
                  (setf i j)))
               ((digit-char-p c)
                (let ((j i))
                  (loop while (and (< j n) (digit-char-p (char text j)))
                        do (incf j))
                  (if (and (= (- j i) 1)
                           (< j n)
                           (find (char-upcase (char text j)) "HFB")
                           (or (= (1+ j) n)
                               (not (mmixal-letter-or-digit-p (char text (1+ j))))))
                      (progn
                        (push (list :local
                                    (digit-char-p c)
                                    (intern (string (char-upcase (char text j))) :keyword))
                              toks)
                        (setf i (1+ j)))
                      (progn
                        (push (list :int (parse-integer text :start i :end j)) toks)
                        (setf i j)))))
               ((char= c #\')
                (incf i)
                (when (>= i n) (mmixal-error "unclosed character constant"))
                (let ((ch (char text i)))
                  (incf i)
                  (unless (and (< i n) (char= (char text i) #\'))
                    (mmixal-error "unclosed character constant"))
                  (incf i)
                  (push (list :int (char-code ch)) toks)))
               ((char= c #\")
                (incf i)
                (let ((j (position #\" text :start i)))
                  (unless j (mmixal-error "unclosed string"))
                  (push (list :str (subseq text i j)) toks)
                  (setf i (1+ j))))
               ((mmixal-letter-p c)
                (let ((j i))
                  (loop while (and (< j n) (mmixal-letter-or-digit-p (char text j)))
                        do (incf j))
                  (push (list :sym (subseq text i j)) toks)
                  (setf i j)))
               (t (mmixal-error "bad character ~A in operand" c))))
    (nreverse toks)))

(defun split-comma-groups (tokens)
  (let ((groups nil)
        (cur nil)
        (depth 0))
    (dolist (tok tokens)
      (cond
        ((and (eq (first tok) :lparen))
         (incf depth)
         (push tok cur))
        ((eq (first tok) :rparen)
         (decf depth)
         (when (minusp depth) (mmixal-error "unbalanced parenthesis"))
         (push tok cur))
        ((and (eq (first tok) :comma) (zerop depth))
         (push (nreverse cur) groups)
         (setf cur nil))
        (t (push tok cur))))
    (unless (zerop depth) (mmixal-error "unbalanced parenthesis"))
    (when (or cur groups)
      (push (nreverse cur) groups))
    (nreverse groups)))

(defun parse-expr-tokens (tokens)
  (let ((i 0))
    (labels ((peek () (and (< i (length tokens)) (nth i tokens)))
             (take () (prog1 (nth i tokens) (incf i)))
             (primary ()
               (let ((tok (take)))
                 (unless tok (mmixal-error "missing expression"))
                 (case (first tok)
                   (:int (list :int (second tok)))
                   (:reg (list :reg (second tok)))
                   (:at (list :at))
                   (:str (list :str (second tok)))
                   (:sym (list :sym (second tok)))
                   (:local (list :local (second tok) (third tok)))
                   (:lparen
                    (let ((e (expr)))
                      (let ((end (take)))
                        (unless (and end (eq (first end) :rparen))
                          (mmixal-error "missing closing parenthesis")))
                      e))
                   (t (mmixal-error "bad expression")))))
             (factor ()
               (let ((tok (peek)))
                 (if (and tok (eq (first tok) :op) (member (second tok) '(:+ :- :~ :$)))
                     (progn (take) (list :unop (second tok) (factor)))
                     (primary))))
             (term ()
               (let ((left (factor)))
                 (loop for tok = (peek)
                       while (and tok (eq (first tok) :op)
                                  (member (second tok) '(:* :/ :% :<< :>> :&)))
                       do (take)
                          (setf left (list :binop (second tok) left (factor))))
                 left))
             (expr ()
               (let ((left (term)))
                 (loop for tok = (peek)
                       while (and tok (eq (first tok) :op)
                                  (member (second tok) '(:+ :- :\| :^)))
                       do (take)
                          (setf left (list :binop (second tok) left (term))))
                 left)))
      (let ((e (expr)))
        (when (< i (length tokens))
          (mmixal-error "extra tokens in expression"))
        e))))

(defun parse-operand-exprs (text prefix)
  (when (zerop (length text))
    (return-from parse-operand-exprs nil))
  (let ((tokens (lex-operand text)))
    (mapcar (lambda (group)
              (when (null group) (mmixal-error "empty operand"))
              (let ((e (parse-expr-tokens group)))
                (qualify-expr e prefix)))
            (split-comma-groups tokens))))

(defun qualify-expr (expr prefix)
  (cond
    ((and (consp expr) (eq (first expr) :sym))
     (list :sym (qualify-symbol prefix (second expr))))
    ((and (consp expr) (eq (first expr) :unop))
     (list :unop (second expr) (qualify-expr (third expr) prefix)))
    ((and (consp expr) (eq (first expr) :binop))
     (list :binop (second expr)
           (qualify-expr (third expr) prefix)
           (qualify-expr (fourth expr) prefix)))
    (t expr)))

(defun pseudo-op-p (name)
  (member name '(:is :loc :prefix :byte :wyde :tetra :octa
                 :greg :local :bspec :espec :set :lda)
          :test #'eq))

(defun backward-alias-p (key)
  (let ((name (symbol-name key)))
    (and (> (length name) 1)
         (char= (char name (1- (length name))) #\B)
         (or (eq key :jmpb)
             (assoc (intern (subseq name 0 (1- (length name))) :keyword)
                    +branch-forward+)))))

(defun opcode-key (name)
  (let ((key (intern (string-upcase name) :keyword)))
    (cond
      ((pseudo-op-p key) key)
      ((or (immediate-mnemonic-p key) (backward-alias-p key))
       (mmixal-error "opcode ~A is chosen automatically" name))
      ((gethash key *op-byte*) key)
      (t (mmixal-error "bad mnemonic ~A" name)))))

(defun instruction-stmts (s file line-no prefix)
  "Parse one physical line into statements. PREFIX is the qualifier so far."
  (let ((text (string-right-trim '(#\Return #\Space #\Tab) s)))
    (when (or (zerop (length text))
              (not (or (mmixal-ws-p (char text 0))
                       (mmixal-letter-or-digit-p (char text 0)))))
      (return-from instruction-stmts nil))
    (parse-instr-at text 0 file line-no prefix)))

(defun parse-instr-at (s start file line-no prefix)
  (let ((i start)
        (n (length s)))
    (when (>= i n) (return-from parse-instr-at nil))
    (cond
      ((mmixal-ws-p (char s i))
       (setf i (skip-ws-index s i))
       (when (or (>= i n) (comment-at-p s i))
         (return-from parse-instr-at nil))
       (read-opcode-stmt s i nil file line-no prefix))
      ((mmixal-letter-or-digit-p (char s i))
       (let* ((j (field-end-index s i))
              (lab (subseq s i j)))
         (setf i (skip-ws-index s j))
         (cond
           ((or (>= i n) (comment-at-p s i))
            (list (make-mstmt :file file :line line-no
                              :label (classify-label lab prefix)
                              :op nil :operands nil)))
           (t (read-opcode-stmt s i lab file line-no prefix)))))
      (t nil))))

(defun classify-label (lab prefix)
  (cond
    ((local-label-string-p lab)
     (unless (char-equal (char lab 1) #\H)
       (mmixal-error "local label ~A is only valid as H in the label field" lab))
     (list :local (digit-char-p (char lab 0))))
    ((every #'mmixal-letter-or-digit-p lab)
     (qualify-symbol prefix lab))
    (t (mmixal-error "bad label ~A" lab))))

(defun read-opcode-stmt (s i raw-label file line-no prefix)
  (let* ((j (field-end-index s i))
         (op (opcode-key (subseq s i j)))
         (k (skip-ws-index s j))
         (label (and raw-label (classify-label raw-label prefix))))
    (multiple-value-bind (operand end)
        (if (or (>= k (length s)) (comment-at-p s k))
            (values "" k)
            (take-operand-text s k))
      (let* ((exprs (parse-operand-exprs operand prefix))
             (stmt (make-mstmt :file file :line line-no
                               :label label :op op :operands exprs))
             (after (skip-ws-index s end)))
        (if (and (< after (length s)) (char= (char s after) #\;))
            (cons stmt (parse-instr-at s (1+ after) file line-no prefix))
            (list stmt))))))

(defun mms-lines (text)
  (let ((lines nil)
        (start 0))
    (loop for i from 0 below (length text)
          when (char= (char text i) #\Newline)
            do (push (subseq text start i) lines)
               (setf start (1+ i)))
    (when (< start (length text))
      (push (subseq text start) lines))
    (nreverse lines)))

(defun parse-mms-text (text filename)
  (let ((stmts nil)
        (prefix ":")
        (line-no 0)
        (pending nil)
        (file filename))
    (dolist (line (mms-lines text))
      (when pending
        (setf line-no (1- (first pending))
              file (second pending)
              pending nil))
      (incf line-no)
      (let ((*mmixal-file* file)
            (*mmixal-line* line-no))
        (cond
          ((line-directive-p line)
           (setf pending (read-line-directive line)))
          (t
           (let ((part (instruction-stmts line file line-no prefix)))
             (dolist (stmt part)
               (when (eq (mstmt-op stmt) :prefix)
                 (setf prefix (prefix-from-stmt stmt prefix))))
             (setf stmts (append stmts part)))))))
    stmts))

(defun line-directive-p (line)
  (let ((s (string-left-trim '(#\Space #\Tab) line)))
    (and (plusp (length s))
         (char= (char s 0) #\#)
         (position #\" s)
         (some #'digit-char-p s))))

(defun read-line-directive (line)
  (let* ((s (string-left-trim '(#\Space #\Tab) line))
         (n (parse-integer s :start 1 :junk-allowed t))
         (q1 (position #\" s))
         (q2 (and q1 (position #\" s :start (1+ q1)))))
    (unless (and n q1 q2)
      (mmixal-error "bad line directive"))
    (list n (subseq s (1+ q1) q2))))

(defun prefix-from-stmt (stmt prefix)
  (unless (null (mstmt-label stmt))
    (mmixal-error "PREFIX does not take a label"))
  (unless (= (length (mstmt-operands stmt)) 1)
    (mmixal-error "PREFIX wants one symbol"))
  (let ((e (first (mstmt-operands stmt))))
    (unless (and (consp e) (eq (first e) :sym))
      (mmixal-error "PREFIX wants a symbol"))
    ;; parse-operand-exprs already qualified the symbol with the old prefix.
    (second e)))

(defun op-kind (op)
  (cond
    ((member op '(:bn :bz :bp :bod :bnn :bnz :bnp :bev
                  :pbn :pbz :pbp :pbod :pbnn :pbnz :pbnp :pbev
                  :pushj :geta))
     :branch)
    ((eq op :jmp) :jmp)
    ((member op '(:trap :trip :swym)) :trap)
    ((eq op :pop) :pop)
    ((eq op :get) :get)
    ((eq op :put) :put)
    ((member op '(:sync :resume)) :xyz)
    ((member op '(:save :unsave)) :save)
    ((member op '(:seth :setmh :setml :setl :inch :incmh :incml :incl
                  :orh :ormh :orml :orl :andnh :andnmh :andnml :andnl))
     :wyde)
    ((member op '(:neg :negu)) :neg)
    ((eq op :set) :set)
    ((member op '(:flot :flotu :sflot :sflotu)) :flot)
    ((or (eq op :lda)
         (and (gethash op *op-byte*)
              (<= #x80 (gethash op *op-byte*) #xBF)))
     :mem)
    ((member op '(:is :loc :prefix :greg :local :bspec :espec
                  :byte :wyde :tetra :octa))
     :pseudo)
    (t :xyz3)))

(defun pure-x-op-p (op)
  (member op '(:preld :prego :prest :stco :syncd :syncid)))

(defstruct mval kind n)

(defun mabs (n) (make-mval :kind :abs :n (u64 n)))
(defun mreg (n) (make-mval :kind :reg :n n))
(defun mval-abs-p (v) (eq (mval-kind v) :abs))
(defun mval-reg-p (v) (eq (mval-kind v) :reg))

(defun defined-sym (table name)
  (let ((sym (gethash name table)))
    (when (and sym (or (msym-predefined sym) (msym-value sym) (eq (msym-kind sym) :label)))
      sym)))

(defun lookup-msym (table name)
  (gethash name table))

(defun bind-symbol (table name kind value)
  (let ((old (gethash name table)))
    (cond
      ((and old (msym-predefined old) (not (msym-redefined old)))
       (setf (msym-kind old) kind
             (msym-value old) value
             (msym-redefined old) t
             (msym-predefined old) nil))
      (old (mmixal-error "redefinition of ~A" name))
      (t (setf (gethash name table)
               (make-msym :name name :kind kind :value value)))))
  name)

(defun update-label (table name addr)
  (let ((sym (gethash name table)))
    (cond
      ((null sym)
       (setf (gethash name table)
             (make-msym :name name :kind :label :value addr)))
      ((eq (msym-kind sym) :label)
       (setf (msym-value sym) addr))
      (t (mmixal-error "redefinition of ~A" name))))
  name)

(defun align-up (pc n)
  (let ((m (mod pc n)))
    (if (zerop m) pc (+ pc (- n m)))))

(defun eval-mexpr (expr table locals here self-index bases)
  (declare (ignore bases))
  (cond
    ((eq (first expr) :int) (mabs (second expr)))
    ((eq (first expr) :reg) (mreg (second expr)))
    ((eq (first expr) :at) (mabs here))
    ((eq (first expr) :str)
     (mmixal-error "string is only valid in BYTE, WYDE, TETRA, or OCTA"))
    ((eq (first expr) :sym)
     (let ((sym (lookup-msym table (second expr))))
       (cond
         ((and sym (eq (msym-kind sym) :reg) (msym-value sym))
          (mreg (msym-value sym)))
         ((and sym (eq (msym-kind sym) :label) (numberp (msym-value sym)))
          (mabs (msym-value sym)))
         ((and sym (eq (msym-kind sym) :abs) (numberp (msym-value sym)))
          (mabs (msym-value sym)))
         (t (error 'mmixal-unresolved)))))
    ((eq (first expr) :local)
     (let* ((digit (second expr))
            (dir (third expr))
            (defs (aref locals digit)))
       (case dir
         (:H (mmixal-error "H is a label, not an operand"))
         (:B (let ((prev (find-if (lambda (pair) (< (car pair) self-index))
                                  defs :from-end t)))
               (cond
                 ((null prev) (mabs 0))
                 ((null (cdr prev)) (error 'mmixal-unresolved))
                 (t (mabs (cdr prev))))))
         (:F (let ((next (find-if (lambda (pair) (> (car pair) self-index)) defs)))
               (if (and next (not (null (cdr next))))
                   (mabs (cdr next))
                   (error 'mmixal-unresolved))))
         (t (mmixal-error "bad local reference")))))
    ((eq (first expr) :unop)
     (let ((arg (eval-mexpr (third expr) table locals here self-index bases)))
       (case (second expr)
         (:+ arg)
         (:-
          (when (mval-reg-p arg) (mmixal-error "unary minus needs a pure value"))
          (mabs (- (mval-n arg))))
         (:~
          (when (mval-reg-p arg) (mmixal-error "complement needs a pure value"))
          (mabs (logxor (mval-n arg) +u64-mask+)))
         (:$
          (when (mval-reg-p arg) (mmixal-error "$ needs a pure value"))
          (mreg (mval-n arg)))
         (t (mmixal-error "bad operator")))))
    ((eq (first expr) :binop)
     (combine-mval (second expr)
                   (eval-mexpr (third expr) table locals here self-index bases)
                   (eval-mexpr (fourth expr) table locals here self-index bases)))
    (t (mmixal-error "bad expression"))))

(define-condition mmixal-unresolved (error) ())

(defun combine-mval (op a b)
  (cond
    ((and (eq op :+) (mval-reg-p a) (mval-abs-p b))
     (mreg (+ (mval-n a) (mval-n b))))
    ((and (eq op :+) (mval-abs-p a) (mval-reg-p b))
     (mreg (+ (mval-n b) (mval-n a))))
    ((and (eq op :-) (mval-reg-p a) (mval-abs-p b))
     (mreg (- (mval-n a) (mval-n b))))
    ((and (eq op :-) (mval-reg-p a) (mval-reg-p b))
     (mabs (- (mval-n a) (mval-n b))))
    ((or (mval-reg-p a) (mval-reg-p b))
     (mmixal-error "register number is not valid with this operator"))
    (t (mabs (pure-binop op (mval-n a) (mval-n b))))))

(defun pure-binop (op a b)
  (let ((a (u64 a))
        (b (u64 b)))
    (case op
      (:+ (u64 (+ a b)))
      (:- (u64 (- a b)))
      (:* (u64 (* a b)))
      (:/
       (when (zerop b) (mmixal-error "division by zero"))
       (floor a b))
      (:%
       (when (zerop b) (mmixal-error "division by zero"))
       (mod a b))
      (:<< (if (>= b 64) 0 (u64 (ash a b))))
      (:>> (if (>= b 64) 0 (ash a (- b))))
      (:& (logand a b))
      (:\| (logior a b))
      (:^ (logxor a b))
      (t (mmixal-error "bad operator")))))

(defun need-reg (val)
  (unless (mval-reg-p val)
    (mmixal-error "expected a register"))
  (unless (<= 0 (mval-n val) 255)
    (mmixal-error "register out of range"))
  (mval-n val))

(defun need-pure (val)
  (unless (mval-abs-p val)
    (mmixal-error "expected a pure value"))
  (mval-n val))

(defun need-byte (val)
  (let ((n (need-pure val)))
    (unless (<= 0 n 255)
      (mmixal-error "value does not fit in a byte"))
    n))

(defun need-wyde (val)
  (let ((n (need-pure val)))
    (unless (<= 0 n #xffff)
      (mmixal-error "value does not fit in a wyde"))
    n))

(defun need-tetra (val)
  (let ((n (need-pure val)))
    (unless (<= 0 n #xffffffff)
      (mmixal-error "value does not fit in a tetra"))
    n))

(defun data-width (op)
  (case op (:byte 1) (:wyde 2) (:tetra 4) (:octa 8)))

(defun data-values (operands table locals here index)
  (let ((out nil))
    (dolist (e operands)
      (if (and (consp e) (eq (first e) :str))
          (dolist (ch (coerce (second e) 'list))
            (push (char-code ch) out))
          (push (need-pure (eval-mexpr e table locals here index nil)) out)))
    (nreverse out)))

(defun stmt-data-size (stmt)
  (let ((width (data-width (mstmt-op stmt)))
        (n 0))
    (dolist (e (mstmt-operands stmt))
      (incf n (if (and (consp e) (eq (first e) :str))
                  (length (second e))
                  1)))
    (* width n)))

(defun collect-local-defs (stmts)
  "Names and source indexes of dH labels. Addresses are filled later."
  (let ((count (make-array 10 :initial-element 0))
        (names (make-array 10 :initial-element nil)))
    (loop for stmt in stmts
          for index from 0
          for lab = (mstmt-label stmt)
          when (and (consp lab) (eq (first lab) :local))
            do (let* ((d (second lab))
                      (k (aref count d))
                      (name (format nil "~~~DH~~~D" d k)))
                 (incf (aref count d))
                 (push (list index name) (aref names d))
                 (setf (mstmt-label stmt) (list :local d name))))
    (dotimes (d 10)
      (setf (aref names d) (nreverse (aref names d))))
    names))

(defun local-address-vector (stmts local-names)
  (let ((v (make-array 10 :initial-element nil)))
    (dotimes (d 10)
      (setf (aref v d)
            (mapcar (lambda (pair)
                      (let ((stmt (nth (first pair) stmts)))
                        (cons (first pair) (mstmt-addr stmt))))
                    (aref local-names d))))
    v))

(defun find-base-reg (bases addr)
  (let ((best nil)
        (best-delta 256))
    (dolist (pair bases)
      (let ((delta (- addr (car pair))))
        (when (and (<= 0 delta 255) (< delta best-delta))
          (setf best (cdr pair)
                best-delta delta))))
    (values best best-delta)))

(defun resolve-mms (stmts filename)
  (declare (ignore filename))
  (let* ((table (make-predef-table))
         (local-names (collect-local-defs stmts))
         (greg 255)
         (bases nil)
         (greg-regs nil)
         (local-max 31)
         (specs nil)
         (spec-open nil)
         (spec-mode 0)
         (spec-bytes nil)
         (forms nil)
         (lines (make-hash-table :test 'eql))
         (image (make-mmixal-image)))
    (labels ((eval-at (stmt expr index here)
               (let ((*mmixal-file* (mstmt-file stmt))
                     (*mmixal-line* (mstmt-line stmt)))
                 (eval-mexpr expr table (local-address-vector stmts local-names)
                             here index bases)))
             (note (addr line file n)
               (dotimes (i n)
                 (setf (gethash (+ addr i) lines) (cons file line)))))
      (let ((index 0)
            (pc 0))
        (dolist (stmt stmts)
          (let ((*mmixal-file* (mstmt-file stmt))
                (*mmixal-line* (mstmt-line stmt))
                (op (mstmt-op stmt))
                (lab (mstmt-label stmt)))
            (cond
              ((null op)
               (when lab
                 (if (and (consp lab) (eq (first lab) :local))
                     nil
                     (update-label table lab pc)))
               (setf (mstmt-addr stmt) pc
                     (mstmt-size stmt) 0))
              ((eq op :prefix)
               (when lab (mmixal-error "PREFIX does not take a label")))
              ((eq op :is)
               (unless (and lab (stringp lab))
                 (mmixal-error "IS needs a symbol"))
               (unless (= (length (mstmt-operands stmt)) 1)
                 (mmixal-error "IS wants one expression"))
               (let ((val (handler-case (eval-at stmt (first (mstmt-operands stmt)) index pc)
                             (mmixal-unresolved ()
                               (mmixal-error "IS cannot be a future reference")))))
                 (bind-symbol table lab
                              (if (mval-reg-p val) :reg :abs)
                              (mval-n val))))
              ((eq op :greg)
               (when (and lab (not (stringp lab)))
                 (mmixal-error "GREG label must be a global symbol"))
               (when (> (length (mstmt-operands stmt)) 1)
                 (mmixal-error "GREG wants one expression"))
               (let* ((val (if (mstmt-operands stmt)
                               (handler-case (eval-at stmt (first (mstmt-operands stmt)) index pc)
                                 (mmixal-unresolved ()
                                   (mmixal-error "GREG cannot be a future reference")))
                               (mabs pc)))
                      (num (need-pure val)))
                 (when (<= greg 32)
                   (mmixal-error "no global registers left"))
                 (decf greg)
                 (when (stringp lab)
                   (bind-symbol table lab :reg greg))
                 (push (cons num greg) bases)
                 (push (cons greg num) greg-regs)
                 (setf (mstmt-addr stmt) pc
                       (mstmt-size stmt) 0)))
              ((eq op :local)
               (when lab (mmixal-error "LOCAL does not take a label"))
               (unless (= (length (mstmt-operands stmt)) 1)
                 (mmixal-error "LOCAL wants a register"))
               (let ((n (need-reg (eval-at stmt (first (mstmt-operands stmt)) index pc))))
                 (setf local-max (max local-max n))))
              ((eq op :bspec)
               (when lab (mmixal-error "BSPEC does not take a label"))
               (when spec-open (mmixal-error "nested BSPEC"))
               (unless (= (length (mstmt-operands stmt)) 1)
                 (mmixal-error "BSPEC wants a mode"))
               (setf spec-mode (need-pure (eval-at stmt (first (mstmt-operands stmt)) index pc))
                     spec-open t
                     spec-bytes nil)
               (unless (<= 0 spec-mode #xffff)
                 (mmixal-error "BSPEC mode does not fit in two bytes")))
              ((eq op :espec)
               (when lab (mmixal-error "ESPEC does not take a label"))
               (unless spec-open (mmixal-error "ESPEC without BSPEC"))
               (let ((pad (mod (- 4 (mod (length spec-bytes) 4)) 4)))
                 (dotimes (i pad) (push 0 spec-bytes))
                 (push (list :mode spec-mode
                             :tetras (bytes-to-tetras (nreverse spec-bytes)))
                       specs))
               (setf spec-open nil spec-bytes nil))
              ((eq op :loc)
               (when (and lab (stringp lab))
                 (update-label table lab pc))
               (when (and lab (consp lab))
                 nil)
               (unless (= (length (mstmt-operands stmt)) 1)
                 (mmixal-error "LOC wants an address"))
               (let ((val (handler-case (eval-at stmt (first (mstmt-operands stmt)) index pc)
                             (mmixal-unresolved ()
                               (mmixal-error "LOC cannot be a future reference")))))
                 (setf pc (need-pure val)))
               (setf (mstmt-addr stmt) pc
                     (mstmt-size stmt) 0))
              ((member op '(:byte :wyde :tetra :octa))
               (let ((width (data-width op)))
                 (unless spec-open
                   (unless (= width 1)
                     (let ((aligned (align-up pc width)))
                       (setf pc aligned))))
                 (when (and spec-open (> width 1))
                   (let ((extra (mod (length spec-bytes) width)))
                     (unless (zerop extra)
                       (dotimes (i (- width extra))
                         (push 0 spec-bytes)))))
                 (when (and lab (stringp lab) (not spec-open))
                   (update-label table lab pc))
                 (let* ((vals (data-values (mstmt-operands stmt) table
                                           (local-address-vector stmts local-names)
                                           pc index))
                        (nbytes (* width (length vals))))
                   (dolist (v vals)
                     (case op
                       (:byte (unless (<= 0 v 255)
                                (mmixal-error "BYTE value does not fit")))
                       (:wyde (unless (<= 0 v #xffff)
                                (mmixal-error "WYDE value does not fit")))
                       (:tetra (unless (<= 0 v #xffffffff)
                                (mmixal-error "TETRA value does not fit")))))
                   (cond
                     (spec-open
                      (dolist (b (emit-data-bytes (list* op vals)))
                        (push b spec-bytes)))
                     (t
                      (note pc (mstmt-line stmt) (mstmt-file stmt) nbytes)
                      (setf (mstmt-addr stmt) pc
                            (mstmt-size stmt) nbytes)
                      (push (list stmt pc (list* op vals)) forms)
                      (incf pc nbytes))))))
              (t
               (when spec-open
                 (mmixal-error "ordinary instructions cannot appear in BSPEC"))
               (let ((aligned (align-up pc 4)))
                 (setf pc aligned))
               (when (and lab (stringp lab))
                 (update-label table lab pc))
               (setf (mstmt-addr stmt) pc
                     (mstmt-size stmt) 4)
               (note pc (mstmt-line stmt) (mstmt-file stmt) 4)
               (push (list stmt pc :inst) forms)
               (incf pc 4))))
          (incf index))
        (when spec-open (mmixal-error "BSPEC without ESPEC"))
        (when (<= greg local-max)
          (mmixal-error "rG=~D does not leave register ~D local" greg local-max))
        (setf (mmixal-image-rg image) greg
              (mmixal-image-specs image) (nreverse specs)
              (mmixal-image-lines image) lines)
        (dolist (pair greg-regs)
          (setf (gethash (car pair) (mmixal-image-values image)) (cdr pair)))
        (maphash (lambda (name sym)
                   (when (and (eq (msym-kind sym) :reg)
                              (not (msym-predefined sym)))
                     (setf (gethash name (mmixal-image-regs image)) (msym-value sym))))
                 table)
        (setf (mmixal-image-symbols image) (exported-symbols table)
              (mmixal-image-bases image) bases)
        (let ((locals (local-address-vector stmts local-names)))
          (loop for stmt in stmts
                for idx from 0
                do (setf (mstmt-meta stmt) (list idx locals local-names))))
        (values (nreverse forms) table local-names image pc)))))

(defun bytes-to-tetras (bytes)
  (loop for i from 0 below (length bytes) by 4
        collect (logior (ash (nth i bytes) 24)
                        (ash (nth (+ i 1) bytes) 16)
                        (ash (nth (+ i 2) bytes) 8)
                        (nth (+ i 3) bytes))))

(defun exported-symbols (table)
  "User symbols, fully qualified. Predefined names stay out until redefined.
:Main is serial 1, matching mmixal."
  (let ((syms nil))
    (maphash (lambda (name sym)
               (declare (ignore name))
               (when (and (not (msym-predefined sym))
                          (member (msym-kind sym) '(:label :abs :reg)))
                 (push sym syms)))
             table)
    (setf syms (sort syms #'string< :key #'msym-name))
    (let* ((main-p (some (lambda (sym) (symbol-is-main (msym-name sym))) syms))
           (n (if main-p 2 1))
           (out nil))
      (dolist (sym syms)
        (let ((serial (if (symbol-is-main (msym-name sym))
                          1
                          (prog1 n (incf n)))))
          (push (make-mmix-symbol
                 :name (msym-name sym)
                 :value (msym-value sym)
                 :kind (if (eq (msym-kind sym) :reg) :register :absolute)
                 :serial serial)
                out)))
      (nreverse out))))

(defun mstmt-index (stmt)
  (first (mstmt-meta stmt)))

(defun stmt-locals (stmt)
  (second (mstmt-meta stmt)))

(defun stmt-local-names (stmt)
  (third (mstmt-meta stmt)))

(defun eval-here (expr stmt table)
  (let ((*mmixal-file* (mstmt-file stmt))
        (*mmixal-line* (mstmt-line stmt)))
    (handler-case
        (eval-mexpr expr table (stmt-locals stmt) (mstmt-addr stmt)
                    (mstmt-index stmt) nil)
      (mmixal-unresolved ()
        (mmixal-error "undefined or future reference")))))

(defun local-target-name (digit dir stmt)
  "Internal label emitted for dF/dB, or NIL when a backward ref has no dH."
  (let ((defs (aref (stmt-local-names stmt) digit))
        (index (mstmt-index stmt)))
    (case dir
      (:H (mmixal-error "H is a label, not an operand"))
      (:F (let ((next (find-if (lambda (pair) (> (first pair) index)) defs)))
            (unless next
              (mmixal-error "no forward local label ~DF" digit))
            (second next)))
      (:B (let ((prev (find-if (lambda (pair) (< (first pair) index))
                               defs :from-end t)))
            (and prev (second prev))))
      (t (mmixal-error "bad local reference")))))

(defun branch-target (expr stmt table)
  "A label name that encode-form can see, or an absolute address."
  (cond
    ((and (consp expr) (eq (first expr) :local))
     (or (local-target-name (second expr) (third expr) stmt) 0))
    ((and (consp expr) (eq (first expr) :sym))
     (let ((sym (lookup-msym table (second expr))))
       (cond
         ((and sym (eq (msym-kind sym) :label))
          (second expr))
         (sym (need-pure (eval-here expr stmt table)))
         (t (mmixal-error "undefined symbol ~A" (second expr))))))
    (t (need-pure (eval-here expr stmt table)))))

(defun rel-delta (pc target)
  (let ((diff (- target pc)))
    (unless (zerop (mod diff 4))
      (mmixal-error "branch target #x~X is not a multiple of 4 from #x~X"
                    target pc))
    (truncate diff 4)))

(defun branch-bytes (forward x delta)
  (multiple-value-bind (op disp) (encode-relative forward delta 16)
    (bytes4 op x (ldb (byte 8 8) disp) (ldb (byte 8 0) disp))))

(defun jmp-bytes (delta)
  (multiple-value-bind (op disp) (encode-relative #xF0 delta 24)
    (bytes4 op
            (ldb (byte 8 16) disp)
            (ldb (byte 8 8) disp)
            (ldb (byte 8 0) disp))))

(defun as-byte-form (bytes)
  (list* :byte bytes))

(defun imm-key (op)
  "Odd opcode keyword. LDA's immediate form is ADDUI."
  (let* ((base (alias-op op))
         (k (intern (concatenate 'string (symbol-name base) "I") :keyword)))
    (unless (gethash k *op-byte*)
      (mmixal-error "immediate form of ~A is not an instruction" op))
    k))

(defun reg-key (op)
  (alias-op op))

(defun field-byte (val)
  (if (mval-reg-p val) (need-reg val) (need-byte val)))

(defun need-special-num (val)
  (let ((n (need-pure val)))
    (unless (<= 0 n 31)
      (mmixal-error "special register out of range"))
    n))

(defun need-xyz (val)
  (let ((n (need-pure val)))
    (unless (<= 0 n #xffffff)
      (mmixal-error "XYZ field does not fit in 24 bits"))
    n))

(defun emit-resolved-forms (chunks table image)
  (let ((forms nil)
        (emitted nil)
        (bases (mmixal-image-bases image)))
    (dolist (chunk chunks)
      (let* ((stmt (first chunk))
             (addr (second chunk))
             (body (third chunk))
             (*mmixal-file* (mstmt-file stmt))
             (*mmixal-line* (mstmt-line stmt)))
        (unless (eql emitted addr)
          (push (list :org addr) forms)
          (setf emitted addr))
        (when (and (mstmt-label stmt) (stringp (mstmt-label stmt)))
          (push (list :label (mstmt-label stmt)) forms))
        (when (and (mstmt-label stmt)
                   (consp (mstmt-label stmt))
                   (eq (first (mstmt-label stmt)) :local))
          (push (list :label (third (mstmt-label stmt))) forms))
        (let ((bytes-forms
                (if (eq body :inst)
                    (instruction-forms stmt table bases)
                    (list body))))
          (dolist (form bytes-forms)
            (push form forms)
            (incf emitted (form-nbytes form))))))
    (nreverse forms)))

(defun instruction-forms (stmt table bases)
  (let* ((op (mstmt-op stmt))
         (exprs (mstmt-operands stmt))
         (*mmixal-file* (mstmt-file stmt))
         (*mmixal-line* (mstmt-line stmt)))
    (ecase (op-kind op)
      (:branch (list (branch-form op exprs stmt table)))
      (:jmp (list (jmp-form exprs stmt table)))
      (:trap (list (trap-form op exprs stmt table)))
      (:pop (list (pop-form exprs stmt table)))
      (:get (list (get-form exprs stmt table)))
      (:put (list (put-form exprs stmt table)))
      (:xyz (list (xyz-form op exprs stmt table)))
      (:save (list (save-form op exprs stmt table)))
      (:wyde (list (wyde-form op exprs stmt table)))
      (:neg (list (neg-form op exprs stmt table)))
      (:set (list (set-form exprs stmt table)))
      (:flot (list (flot-form op exprs stmt table)))
      (:mem (list (mem-form op exprs stmt table bases)))
      (:xyz3 (list (xyz3-form op exprs stmt table)))
      (:pseudo (mmixal-error "internal pseudo-op in the instruction stream")))))

(defun branch-x (op expr stmt table)
  (let ((v (eval-here expr stmt table)))
    (if (and (eq op :pushj) (mval-abs-p v))
        (need-byte v)
        (need-reg v))))

(defun branch-form (op exprs stmt table)
  (unless (= (length exprs) 2)
    (mmixal-error "~A wants a register and a target" op))
  (let ((x (branch-x op (first exprs) stmt table))
        (target (branch-target (second exprs) stmt table))
        (forward (cdr (assoc op +branch-forward+))))
    (if (stringp target)
        (list op x target)
        (as-byte-form
         (branch-bytes forward x (rel-delta (mstmt-addr stmt) target))))))

(defun jmp-form (exprs stmt table)
  (unless (= (length exprs) 1)
    (mmixal-error "JMP wants a target"))
  (let ((target (branch-target (first exprs) stmt table)))
    (if (stringp target)
        (list :jmp target)
        (as-byte-form (jmp-bytes (rel-delta (mstmt-addr stmt) target))))))

(defun trap-form (op exprs stmt table)
  (labels ((val (i) (eval-here (nth i exprs) stmt table)))
    (cond
      ((eq op :swym)
       (list :swym (if exprs (need-xyz (val 0)) 0)))
      (t
       (unless (<= (length exprs) 3)
         (mmixal-error "~A wants at most three operands" op))
       (list op
             (if exprs (field-byte (val 0)) 0)
             (if (second exprs) (field-byte (val 1)) 0)
             (if (third exprs) (field-byte (val 2)) 0))))))

(defun pop-form (exprs stmt table)
  (unless (<= 1 (length exprs) 2)
    (mmixal-error "POP wants a count and an optional return address"))
  (list :pop
        (field-byte (eval-here (first exprs) stmt table))
        (if (second exprs)
            (need-wyde (eval-here (second exprs) stmt table))
            0)))

(defun get-form (exprs stmt table)
  (unless (= (length exprs) 2)
    (mmixal-error "GET wants a register and a special register"))
  (list :get
        (need-reg (eval-here (first exprs) stmt table))
        (need-special-num (eval-here (second exprs) stmt table))))

(defun put-form (exprs stmt table)
  (unless (= (length exprs) 2)
    (mmixal-error "PUT wants a special register and a value"))
  (let ((spec (need-special-num (eval-here (first exprs) stmt table)))
        (z (eval-here (second exprs) stmt table)))
    (if (mval-reg-p z)
        (list :put spec (need-reg z))
        (list :puti spec (need-byte z)))))

(defun xyz-form (op exprs stmt table)
  (unless (<= (length exprs) 1)
    (mmixal-error "~A wants one optional operand" op))
  (list op (if exprs (need-xyz (eval-here (first exprs) stmt table)) 0)))

(defun save-form (op exprs stmt table)
  (unless (= (length exprs) 1)
    (mmixal-error "~A wants a register" op))
  ;; SAVE $X / UNSAVE $X put the register in the high byte of XYZ.
  (list op (ash (need-reg (eval-here (first exprs) stmt table)) 16)))

(defun wyde-form (op exprs stmt table)
  (unless (= (length exprs) 2)
    (mmixal-error "~A wants a register and a wyde" op))
  (list op
        (need-reg (eval-here (first exprs) stmt table))
        (need-wyde (eval-here (second exprs) stmt table))))

(defun neg-form (op exprs stmt table)
  (let ((x (need-reg (eval-here (first exprs) stmt table)))
        (y 0)
        (z nil))
    (cond
      ((= (length exprs) 2)
       (setf z (eval-here (second exprs) stmt table)))
      ((= (length exprs) 3)
       (setf y (need-byte (eval-here (second exprs) stmt table))
             z (eval-here (third exprs) stmt table)))
      (t (mmixal-error "~A wants two or three operands" op)))
    (if (mval-reg-p z)
        (list op x y (need-reg z))
        (list (imm-key op) x y (need-byte z)))))

(defun set-form (exprs stmt table)
  (unless (= (length exprs) 2)
    (mmixal-error "SET wants two operands"))
  (let ((x (need-reg (eval-here (first exprs) stmt table)))
        (y (eval-here (second exprs) stmt table)))
    ;; A pure SET is one SETL. It must fit in 16 bits.
    (if (mval-reg-p y)
        (list :set x (need-reg y))
        (list :setl x (need-wyde y)))))

(defun flot-form (op exprs stmt table)
  (let ((x nil) (y 0) (z nil))
    (cond
      ((= (length exprs) 2)
       (setf x (need-reg (eval-here (first exprs) stmt table))
             z (eval-here (second exprs) stmt table)))
      ((= (length exprs) 3)
       (setf x (need-reg (eval-here (first exprs) stmt table))
             y (need-byte (eval-here (second exprs) stmt table))
             z (eval-here (third exprs) stmt table)))
      (t (mmixal-error "~A wants two or three operands" op)))
    (if (mval-reg-p z)
        (list (reg-key op) x y (need-reg z))
        (list (imm-key op) x y (need-byte z)))))

(defun mem-x (op val)
  (cond
    ((or (pure-x-op-p op) (eq op :pushgo))
     (field-byte val))
    (t (need-reg val))))

(defun mem-form (op exprs stmt table bases)
  (unless (<= 2 (length exprs) 3)
    (mmixal-error "~A wants two or three operands" op))
  (let ((x (mem-x op (eval-here (first exprs) stmt table))))
    (if (= (length exprs) 3)
        (let ((y (eval-here (second exprs) stmt table))
              (z (eval-here (third exprs) stmt table)))
          (unless (mval-reg-p y)
            (mmixal-error "~A base must be a register" op))
          (if (mval-reg-p z)
              (list (reg-key op) x (need-reg y) (need-reg z))
              (list (imm-key op) x (need-reg y) (need-byte z))))
        (let ((y (eval-here (second exprs) stmt table)))
          (cond
            ((mval-reg-p y)
             ;; LDO $X,$Y is LDO $X,$Y,0, and 0 is an immediate.
             (list (imm-key op) x (need-reg y) 0))
            (t
             (multiple-value-bind (reg delta)
                 (find-base-reg bases (need-pure y))
               (unless reg
                 (mmixal-error "no global base for address #x~X" (need-pure y)))
               (list (imm-key op) x reg delta))))))))

(defun xyz3-form (op exprs stmt table)
  (unless (<= 2 (length exprs) 3)
    (mmixal-error "~A wants two or three operands" op))
  (let ((x (need-reg (eval-here (first exprs) stmt table)))
        (y 0)
        (z nil))
    (if (= (length exprs) 2)
        (setf z (eval-here (second exprs) stmt table))
        (setf y (need-reg (eval-here (second exprs) stmt table))
              z (eval-here (third exprs) stmt table)))
    (if (mval-reg-p z)
        (list (reg-key op) x y (need-reg z))
        (list (imm-key op) x y (need-byte z)))))

(defun read-text-file (path)
  (with-open-file (s path)
    (let ((out (make-string-output-stream)))
      (loop for line = (read-line s nil nil)
            while line
            do (write-line line out))
      (get-output-stream-string out))))

(defun mms-text (source)
  "SOURCE is program text, a pathname, or a filename with no spaces or newlines."
  (cond
    ((pathnamep source)
     (values (read-text-file source) (namestring source)))
    ((stringp source)
     (if (and (not (find #\Newline source))
              (not (find #\Space source))
              (probe-file source))
         (values (read-text-file source) source)
         (values source "input.mms")))
    (t (error "MMIXAL source must be a string or a pathname"))))

(defun assemble-mms (source)
  "Assemble MMIXAL text or a .mms file.
Returns (values segments origin labels image), the same segment list as
assemble plus the GREG allocation on IMAGE."
  (multiple-value-bind (text filename) (mms-text source)
    (let ((*mmixal-file* filename))
      (multiple-value-bind (chunks table local-names image pc)
          (resolve-mms (parse-mms-text text filename) filename)
        (declare (ignore local-names pc))
        (let ((forms (emit-resolved-forms chunks table image)))
          (multiple-value-bind (segments origin labels)
              (assemble (list* 'program forms))
            (values segments origin labels image)))))))

(defun image-entry (image segments)
  "Same entry as load-mmo: :Main, else the first tetra below Data_Segment."
  (or (loop for sym in (mmixal-image-symbols image)
            when (and (eq (mmix-symbol-kind sym) :absolute)
                      (symbol-is-main (mmix-symbol-name sym)))
              return (mmix-symbol-value sym))
      (loop for seg in segments
            when (and (plusp (length (cdr seg)))
                      (< (car seg) +data-segment+))
              return (car seg))
      0))

(defun load-mms (vm source)
  "Assemble SOURCE and write it into VM. Sets rG, GREG values, lines, and symbols."
  (multiple-value-bind (segments origin labels image) (assemble-mms source)
    (declare (ignore origin))
    (dolist (seg segments)
      (loop for b across (cdr seg)
            for i from 0
            do (mem-set-u8 vm (+ (car seg) i) b :internal t)))
    (set-special vm +r-g+ (mmixal-image-rg image))
    (maphash (lambda (reg val) (set-reg vm reg val))
             (mmixal-image-values image))
    (setf (vm-lines vm) (mmixal-image-lines image)
          (vm-symbols vm) (mmixal-image-symbols image)
          (vm-labels vm) labels)
    (dolist (sym (mmixal-image-symbols image))
      (setf (gethash (mmix-symbol-name sym) (vm-labels vm))
            (mmix-symbol-value sym)))
    (setf (vm-pc vm) (u64 (image-entry image segments))
          (vm-halted vm) nil
          (vm-cycles vm) 0
          (vm-mems vm) 0
          (vm-oops vm) 0
          (vm-mem-cost vm) 0
          (vm-fault vm) nil)
    (sync-stack vm)
    vm))

(defun make-mmo-buf ()
  (make-array 0 :element-type '(unsigned-byte 8) :fill-pointer 0 :adjustable t))

(defun mmo-u32 (buf w)
  (let ((w (u32 w)))
    (vector-push-extend (ldb (byte 8 24) w) buf)
    (vector-push-extend (ldb (byte 8 16) w) buf)
    (vector-push-extend (ldb (byte 8 8) w) buf)
    (vector-push-extend (ldb (byte 8 0) w) buf)))

(defun mmo-u64 (buf w)
  (let ((w (u64 w)))
    (mmo-u32 buf (ldb (byte 32 32) w))
    (mmo-u32 buf (ldb (byte 32 0) w))))

(defun emit-content-tetra (buf tetra)
  (when (= (ldb (byte 8 24) tetra) +mmo-esc+)
    (mmo-u32 buf #x98000001))
  (mmo-u32 buf tetra))

(defun emit-lop-loc (buf addr)
  (let ((y (ldb (byte 8 56) addr))
        (rest (ldb (byte 56 0) addr)))
    (if (<= rest #xffffffff)
        (progn
          (mmo-u32 buf (logior #x98010000 (ash y 8) 1))
          (mmo-u32 buf rest))
        (progn
          (mmo-u32 buf (logior #x98010000 (ash y 8) 2))
          (mmo-u32 buf (ldb (byte 32 32) rest))
          (mmo-u32 buf (ldb (byte 32 0) rest))))))

(defun emit-lop-file (buf n name)
  (let* ((raw (map 'list #'char-code name))
         (pad (mod (- 4 (mod (length raw) 4)) 4)))
    (when (= pad 4) (setf pad 0))
    (let ((bytes (append raw (make-list pad :initial-element 0))))
      (mmo-u32 buf (logior #x98060000 (ash n 8) (floor (length bytes) 4)))
      (loop for i from 0 below (length bytes) by 4
            do (mmo-u32 buf (logior (ash (nth i bytes) 24)
                                    (ash (nth (+ i 1) bytes) 16)
                                    (ash (nth (+ i 2) bytes) 8)
                                    (nth (+ i 3) bytes)))))))

(defun line-note (lines addr)
  (or (gethash addr lines)
      (gethash (+ addr 1) lines)
      (gethash (+ addr 2) lines)
      (gethash (+ addr 3) lines)))

(defun ensure-mmo-file (buf name file-ids)
  (unless (gethash name file-ids)
    (let ((n (1+ (hash-table-count file-ids))))
      (setf (gethash name file-ids) n)
      (emit-lop-file buf n name))))

(defun emit-mmo-segment (buf seg lines file-ids)
  (let* ((addr (car seg))
         (data (cdr seg))
         (skew (mod addr 4))
         (base (- addr skew))
         (raw-len (+ skew (length data)))
         (pad (mod (- 4 (mod raw-len 4)) 4)))
    (when (= pad 4) (setf pad 0))
    (let ((raw (make-array (+ raw-len pad)
                           :element-type '(unsigned-byte 8)
                           :initial-element 0)))
      (loop for i from 0 below (length data)
            do (setf (aref raw (+ skew i)) (aref data i)))
      (emit-lop-loc buf base)
      (loop for i from 0 below (length raw) by 4
            for tetra-addr = (+ base i)
            for tetra = (logior (ash (aref raw i) 24)
                                (ash (aref raw (+ i 1)) 16)
                                (ash (aref raw (+ i 2)) 8)
                                (aref raw (+ i 3)))
            do (let ((note (and (< tetra-addr +data-segment+)
                                (line-note lines tetra-addr))))
                 (when note
                   (ensure-mmo-file buf (car note) file-ids)
                   (mmo-u32 buf (logior #x98070000
                                        (ldb (byte 16 0) (cdr note))))))
               (emit-content-tetra buf tetra)))))

(defstruct trie-node
  char
  (j 0)
  bytes
  (serial 0)
  left mid right)

(defun abs-value-encoding (value)
  "j and the explicit bytes. Data_Segment addresses use j = 9..14."
  (let ((value (u64 value)))
    (loop for k from 1 to 6
          when (= (ash value (- (* 8 k)))
                  (ash +data-segment+ (- (* 8 k))))
            do (return-from abs-value-encoding
                 (cons (+ k 8)
                       (loop for shift from (* 8 (1- k)) downto 0 by 8
                             collect (ldb (byte 8 shift) value)))))
    (let ((n (max 1 (ceiling (integer-length value) 8))))
      (cons n
            (loop for shift from (* 8 (1- n)) downto 0 by 8
                  collect (ldb (byte 8 shift) value))))))

(defun trie-set-value (node sym)
  (let ((enc (if (eq (mmix-symbol-kind sym) :register)
                 (cons 15 (list (ldb (byte 8 0) (mmix-symbol-value sym))))
                 (abs-value-encoding (mmix-symbol-value sym)))))
    (setf (trie-node-j node) (car enc)
          (trie-node-bytes node) (cdr enc)
          (trie-node-serial node) (mmix-symbol-serial sym))))

(defun trie-insert (node name index sym)
  (let ((ch (char name index))
        (last (= index (1- (length name)))))
    (cond
      ((null node)
       (let ((n (make-trie-node :char ch)))
         (if last
             (trie-set-value n sym)
             (setf (trie-node-mid n)
                   (trie-insert nil name (1+ index) sym)))
         n))
      ((char< ch (trie-node-char node))
       (setf (trie-node-left node)
             (trie-insert (trie-node-left node) name index sym))
       node)
      ((char> ch (trie-node-char node))
       (setf (trie-node-right node)
             (trie-insert (trie-node-right node) name index sym))
       node)
      (t
       (when last (trie-set-value node sym))
       (unless last
         (setf (trie-node-mid node)
               (trie-insert (trie-node-mid node) name (1+ index) sym)))
       node))))

(defun serial-bytes (n)
  (cond
    ((< n 128) (list (+ n 128)))
    (t
     (let ((j (+ n 128)))
       (list (ldb (byte 7 7) j) (ldb (byte 7 0) j))))))

(defun emit-trie (node)
  (when node
    (let ((left (emit-trie (trie-node-left node)))
          (mid (emit-trie (trie-node-mid node)))
          (right (emit-trie (trie-node-right node)))
          (m (trie-node-j node))
          (code (char-code (trie-node-char node))))
      (when left (setf m (logior m #x40)))
      (when mid (setf m (logior m #x20)))
      (when right (setf m (logior m #x10)))
      (when (> code 255) (setf m (logior m #x80)))
      (append (list m)
              left
              (if (> code 255)
                  (list (ldb (byte 8 8) code) (ldb (byte 8 0) code))
                  (list code))
              (trie-node-bytes node)
              (when (plusp (trie-node-j node))
                (serial-bytes (trie-node-serial node)))
              mid
              right))))

(defun emit-stab (buf symbols)
  (mmo-u32 buf #x980B0000)
  (let ((root nil))
    (dolist (sym symbols)
      (setf root (trie-insert root (mmix-symbol-name sym) 0 sym)))
    (dolist (b (emit-trie root))
      (vector-push-extend (u8 b) buf)))
  (loop until (zerop (mod (length buf) 4))
        do (vector-push-extend 0 buf))
  (mmo-u32 buf #x980C0000))

(defun image-to-mmo (segments image)
  (let ((buf (make-mmo-buf))
        (file-ids (make-hash-table :test 'equal)))
    (mmo-u32 buf #x98090101)
    (mmo-u32 buf (ldb (byte 32 0) (get-universal-time)))
    (dolist (seg segments)
      (when (plusp (length (cdr seg)))
        (emit-mmo-segment buf seg (mmixal-image-lines image) file-ids)))
    (dolist (spec (mmixal-image-specs image))
      (mmo-u32 buf (logior #x98080000 (ldb (byte 16 0) (getf spec :mode))))
      (dolist (tetra (getf spec :tetras))
        (emit-content-tetra buf tetra)))
    (let ((rg (mmixal-image-rg image)))
      (mmo-u32 buf (logior #x980A0000 rg))
      (loop for g from rg below 256
            do (mmo-u64 buf (gethash g (mmixal-image-values image) 0))))
    (when (mmixal-image-symbols image)
      (emit-stab buf (mmixal-image-symbols image)))
    buf))

(defun write-mmo (source &optional dest)
  "Assemble SOURCE with assemble-mms and return the .mmo octets.
Writes DEST when it is a pathname or a filename."
  (multiple-value-bind (segments origin labels image) (assemble-mms source)
    (declare (ignore origin labels))
    (let ((bytes (image-to-mmo segments image)))
      (when dest
        (with-open-file (s dest :direction :output
                           :element-type '(unsigned-byte 8)
                           :if-exists :supersede
                           :if-does-not-exist :create)
          (write-sequence bytes s)))
      bytes)))
