(in-package #:cl-mmix)

;;; Binary64 operations. The control flow follows MMIXware's fmult, fdivide,
;;; fplus, fcomp, fepscomp, fintegerize, fixit, floatit, froot, and fremstep.
;;; Registers hold the IEEE bit pattern; these functions never cons a float.

(defun deliver-nan (yt zt y z)
  "Propagate a NaN. Two NaNs yield Z, quieted, and I if Y was signaling."
  (when (and (= yt +ft-nan+) (= zt +ft-nan+) (not (quietp y)))
    (fp-raise +i-bit+))
  (if (= zt +ft-nan+)
      (quieten z)
      (quieten y)))

(defun zero-from-signs (ys zs)
  "Signed zero from an exact cancellation or a sum of zeros."
  (apply-sign 0
              (cond ((char= ys zs) ys)
                    ((= *cur-round* +round-down+) #\-)
                    (t #\+))))

(defun fmult (y z)
  (multiple-value-bind (yt yf ye ys) (funpack y)
    (multiple-value-bind (zt zf ze zs) (funpack z)
      (let ((xs (sign-product ys zs)))
        (cond
          ((or (= yt +ft-nan+) (= zt +ft-nan+))
           (deliver-nan yt zt y z))
          ((or (and (= yt +ft-zro+) (or (= zt +ft-zro+) (= zt +ft-num+)))
               (and (= yt +ft-num+) (= zt +ft-zro+)))
           (apply-sign 0 xs))
          ((or (and (= yt +ft-num+) (= zt +ft-inf+))
               (and (= yt +ft-inf+) (or (= zt +ft-num+) (= zt +ft-inf+))))
           (apply-sign +fp-inf+ xs))
          ((or (and (= yt +ft-zro+) (= zt +ft-inf+))
               (and (= yt +ft-inf+) (= zt +ft-zro+)))
           (fp-raise +i-bit+)
           (apply-sign +standard-nan+ xs))
          (t
           (let ((xe (- (+ ye ze) #x3fd)))
             (multiple-value-bind (lo hi) (fp-mul128 yf (fp-shl zf 9))
               (let ((xf hi))
                 (if (>= (fp-hi hi) #x400000)
                     (setf xf hi)
                     (setf xf (fp-shl hi 1)
                           xe (1- xe)))
                 (when (plusp lo)
                   (setf xf (logior xf 1)))
                 (fpack xf xe xs *cur-round*))))))))))

(defun fdivide (y z)
  (multiple-value-bind (yt yf ye ys) (funpack y)
    (multiple-value-bind (zt zf ze zs) (funpack z)
      (let ((xs (sign-product ys zs)))
        (cond
          ((or (= yt +ft-nan+) (= zt +ft-nan+))
           (deliver-nan yt zt y z))
          ((or (and (= yt +ft-zro+) (or (= zt +ft-inf+) (= zt +ft-num+)))
               (and (= yt +ft-num+) (= zt +ft-inf+)))
           (apply-sign 0 xs))
          ((and (= yt +ft-num+) (= zt +ft-zro+))
           (fp-raise +z-bit+)
           (apply-sign +fp-inf+ xs))
          ((and (= yt +ft-inf+) (or (= zt +ft-num+) (= zt +ft-zro+)))
           (apply-sign +fp-inf+ xs))
          ((or (and (= yt +ft-zro+) (= zt +ft-zro+))
               (and (= yt +ft-inf+) (= zt +ft-inf+)))
           (fp-raise +i-bit+)
           (apply-sign +standard-nan+ xs))
          (t
           (let ((xe (+ (- ye ze) #x3fd)))
             (multiple-value-bind (q r) (fp-div128 yf 0 (fp-shl zf 9))
               (when (>= (fp-hi q) #x800000)
                 (setf r (logior r (logand q 1)))
                 (setf q (fp-shr q 1))
                 (incf xe))
               (when (plusp r)
                 (setf q (logior q 1)))
               (fpack q xe xs *cur-round*)))))))))

(defun align-addend (zf d ys zs xe yf)
  "Shift the smaller addend. Returns (values zf d xe yf)."
  (cond ((<= d 2)
         (values (fp-shr zf d) d xe yf))
        ((> d 54)
         (values 1 d xe yf))
        (t
         (when (char/= ys zs)
           (decf d)
           (decf xe)
           (setf yf (fp-shl yf 1)))
         (let* ((o zf)
                (shifted (fp-shr o d)))
           (unless (= (fp-shl shifted d) (u64 o))
             (setf shifted (logior shifted 1)))
           (values shifted d xe yf)))))

(defun fplus (y z)
  (multiple-value-bind (yt yf ye ys) (funpack y)
    (multiple-value-bind (zt zf ze zs) (funpack z)
      (cond
        ((or (= yt +ft-nan+) (= zt +ft-nan+))
         (deliver-nan yt zt y z))
        ((and (= yt +ft-zro+) (= zt +ft-num+))
         (fpack zf ze zs +round-off+))
        ((and (= yt +ft-num+) (= zt +ft-zro+))
         (fpack yf ye ys +round-off+))
        ((and (= yt +ft-inf+) (= zt +ft-inf+))
         (if (char/= ys zs)
             (progn (fp-raise +i-bit+) (apply-sign +standard-nan+ zs))
             (apply-sign +fp-inf+ zs)))
        ((or (and (= yt +ft-num+) (= zt +ft-inf+))
             (and (= yt +ft-zro+) (= zt +ft-inf+)))
         (apply-sign +fp-inf+ zs))
        ((or (and (= yt +ft-inf+) (= zt +ft-num+))
             (and (= yt +ft-inf+) (= zt +ft-zro+)))
         (apply-sign +fp-inf+ ys))
        ((and (= yt +ft-num+) (= zt +ft-num+)
              (/= (logxor (u64 y) +fp-sign+) (u64 z)))
         (let ((xe ye) (xs ys) (d 0) (xf 0))
           (when (or (< ye ze)
                     (and (= ye ze) (< yf zf)))
             (rotatef yf zf)
             (rotatef ye ze)
             (rotatef ys zs)
             (setf xs ys xe ye))
           (setf d (- ye ze))
           (when (plusp d)
             (multiple-value-setq (zf d xe yf)
               (align-addend zf d ys zs xe yf)))
           (if (char= ys zs)
               (setf xf (u64 (+ yf zf)))
               (setf xf (u64 (- yf zf))))
           (cond ((zerop xf)
                  (zero-from-signs ys zs))
                 ((>= (fp-hi xf) #x800000)
                  (let ((lost (logand xf 1)))
                    (setf xf (logior (fp-shr xf 1) lost))
                    (incf xe)
                    (fpack xf xe xs *cur-round*)))
                 (t
                  (loop while (< (fp-hi xf) #x400000)
                        do (decf xe)
                           (setf xf (fp-shl xf 1)))
                  (fpack xf xe xs *cur-round*)))))
        (t (zero-from-signs ys zs))))))

(defun fsub (y z)
  "Negate Z unless it is a NaN, then add."
  (unless (= (fcomp z 0) 2)
    (setf z (logxor (u64 z) +fp-sign+)))
  (fplus y z))

(defun fcomp (y z)
  "−1, 0, +1, or 2 when unordered. Does not raise I; the caller does."
  (multiple-value-bind (yt yf ye ys) (funpack y)
    (declare (ignore yf ye))
    (multiple-value-bind (zt zf ze zs) (funpack z)
      (declare (ignore zf ze))
      (cond
        ((or (= yt +ft-nan+) (= zt +ft-nan+)) 2)
        ((and (= yt +ft-zro+) (= zt +ft-zro+)) 0)
        (t
         (let ((x (cond ((char/= ys zs) 1)
                        ((> (u64 y) (u64 z)) 1)
                        ((< (u64 y) (u64 z)) -1)
                        (t 0))))
           (cond ((zerop x) 0)
                 ((char= ys #\-) (- x))
                 (t x))))))))

(defun fepscomp (y z e sim)
  "1 when SIM is true and y ~ z (e), or SIM is false and y ≈ z (e).
2 when e is negative or any operand is a NaN. Otherwise 0."
  (multiple-value-bind (et ef ee es) (funpack e)
    (when (char= es #\-) (return-from fepscomp 2))
    (case et
      (#.+ft-nan+ (return-from fepscomp 2))
      (#.+ft-inf+ (setf ee 10000)))
    (multiple-value-bind (yt yf ye ys) (funpack y)
      (multiple-value-bind (zt zf ze zs) (funpack z)
        (cond
          ((or (= yt +ft-nan+) (= zt +ft-nan+)) 2)
          ((and (= yt +ft-inf+) (= zt +ft-inf+))
           (if (or (char= ys zs) (>= ee 1023)) 1 0))
          ((or (and (= yt +ft-inf+) (or (= zt +ft-num+) (= zt +ft-zro+)))
               (and (= zt +ft-inf+) (or (= yt +ft-num+) (= yt +ft-zro+))))
           (if (and sim (>= ee 1022)) 1 0))
          ((and (= yt +ft-zro+) (= zt +ft-zro+)) 1)
          ((and (or (and (= yt +ft-zro+) (= zt +ft-num+))
                    (and (= yt +ft-num+) (= zt +ft-zro+)))
                (not sim))
           0)
          (t
           (when (and (< ye 0) (/= yt +ft-zro+))
             (setf yf (fp-shl y 2) ye 0))
           (when (and (< ze 0) (/= zt +ft-zro+))
             (setf zf (fp-shl z 2) ze 0))
           (when (or (< ye ze)
                     (and (= ye ze) (< yf zf)))
             (rotatef yf zf)
             (rotatef ye ze)
             (rotatef ys zs))
           (when (= ze +zero-exponent+)
             (setf ze ye))
           (let ((d (- ye ze)))
             (unless sim (decf ee d))
             (when (>= ee 1023) (return-from fepscomp 1))
             (let ((o 0) (oo 0))
               (if (> d 54)
                   (setf o 0 oo zf)
                   (setf o (fp-shr zf d)
                         oo (fp-shl o d)))
               (when (/= oo (u64 zf))
                 (when (< ee 1020) (return-from fepscomp 0))
                 (setf o (u64 (+ o (if (char= ys zs) 0 1)))))
               (setf o (if (char= ys zs)
                           (u64 (- yf o))
                           (u64 (+ yf o))))
               (when (zerop o) (return-from fepscomp 1))
               (when (< ee 968) (return-from fepscomp 0))
               (if (>= ee 1021)
                   (setf ef (fp-shl ef (- ee 1021)))
                   (setf ef (fp-shr ef (- 1021 ee))))
               (if (<= o ef) 1 0)))))))))

(defun fintegerize (z r)
  (multiple-value-bind (zt zf ze zs) (funpack z)
    (when (zerop r) (setf r *cur-round*))
    (cond
      ((= zt +ft-nan+)
       (if (quietp z) (u64 z) (quieten z)))
      ((or (= zt +ft-inf+) (= zt +ft-zro+)) (u64 z))
      ((>= ze 1074) (fpack zf ze zs +round-off+))
      (t
       (let ((xf (if (<= ze 1020)
                     1
                     (let ((shifted (fp-shr zf (- 1074 ze))))
                       (if (= (fp-shl shifted (- 1074 ze)) (u64 zf))
                           shifted
                           (logior shifted 1))))))
         (setf xf (logandc2 (round-adjust xf zs r) 3))
         (if (>= ze 1022)
             (fpack (fp-shl xf (- 1074 ze)) ze zs +round-off+)
             (apply-sign (if (plusp (fp-lo xf)) #x3ff0000000000000 0) zs)))))))

(defun w-overflow-p (ze zf zs)
  (or (> ze 1085)
      (and (= ze 1085)
           (or (> (fp-hi zf) #x400000)
               (and (= (fp-hi zf) #x400000)
                    (or (plusp (fp-lo zf))
                        (char/= zs #\-)))))))

(defun fixit (z r)
  (multiple-value-bind (zt zf ze zs) (funpack z)
    (declare (ignore zf ze zs))
    (when (zerop r) (setf r *cur-round*))
    (cond
      ((or (= zt +ft-nan+) (= zt +ft-inf+))
       (fp-raise +i-bit+)
       (u64 z))
      ((= zt +ft-zro+) 0)
      (t
       (let ((rounded (fintegerize z r)))
         (multiple-value-bind (rt zf ze zs) (funpack rounded)
           (if (= rt +ft-zro+)
               0
               (let ((o (if (<= ze 1076)
                            (fp-shr zf (- 1076 ze))
                            (progn
                              (when (w-overflow-p ze zf zs)
                                (fp-raise +w-bit+))
                              (when (>= ze 1140)
                                (return-from fixit 0))
                              (fp-shl zf (- ze 1076))))))
                 (if (char= zs #\-) (u64 (- o)) (u64 o))))))))))

(defun floatit (z r unsigned short)
  "Convert an integer octa to binary64. SHORT rounds through binary32 first."
  (setf *fp-exceptions* 0)
  (setf z (u64 z))
  (when (zerop z) (return-from floatit 0))
  (when (zerop r) (setf r *cur-round*))
  (let ((s #\+)
        (e 1076))
    (when (and (zerop unsigned) (logbitp 63 z))
      (setf s #\- z (u64 (- z))))
    (loop while (< (fp-hi z) #x400000)
          do (decf e) (setf z (fp-shl z 1)))
    (loop while (>= (fp-hi z) #x800000)
          do (incf e)
             (let ((lost (logand z 1)))
               (setf z (logior (fp-shr z 1) lost))))
    (when (plusp short)
      (let ((tetra (sfpack z e s r))
            (saved 0))
        (setf saved *fp-exceptions*)
        (multiple-value-bind (ty f e2 s2) (sfunpack tetra)
          (declare (ignore ty))
          (setf z f e e2 s s2))
        (setf *fp-exceptions* saved)))
    (fpack z e s r)))

(defun froot (z r)
  (multiple-value-bind (zt zf ze zs) (funpack z)
    (when (zerop r) (setf r *cur-round*))
    (cond
      ((and (char= zs #\-) (/= zt +ft-zro+))
       (fp-raise +i-bit+)
       (apply-sign +standard-nan+ zs))
      ((= zt +ft-nan+)
       (if (quietp z) (u64 z) (quieten z)))
      ((or (= zt +ft-inf+) (= zt +ft-zro+))
       (u64 z))
      (t
       (let ((xf 2)
             (rf 0)
             (xe (ash (+ ze #x3fe) -1)))
         (when (logtest ze 1)
           (setf zf (fp-shl zf 1)))
         (setf rf (u64 (1- (ash (fp-hi zf) -22))))
         (loop for k from 53 downto 1
               do (setf rf (fp-shl rf 2)
                        xf (fp-shl xf 1))
                  (cond ((>= k 43)
                         (setf rf (u64 (+ rf (logand (ash (fp-hi zf)
                                                          (- (* 2 (- k 43))))
                                                     3)))))
                        ((>= k 27)
                         (setf rf (u64 (+ rf (logand (ash (fp-lo zf)
                                                          (- (* 2 (- k 27))))
                                                     3))))))
                  (when (or (> (fp-hi rf) (fp-hi xf))
                            (and (>= (fp-hi rf) (fp-hi xf))
                                 (> (fp-lo rf) (fp-lo xf))))
                    (setf xf (fp-inc-lo xf))
                    (setf rf (u64 (- rf xf)))
                    (setf xf (fp-inc-lo xf))))
         (when (plusp rf)
           (setf xf (u64 (1+ xf))))
         (fpack xf xe #\+ r))))))

(defun fremstep (y z delta)
  "IEEE remainder. DELTA of 2500 finishes every binary64 case in one call."
  (multiple-value-bind (yt yf ye ys) (funpack y)
    (multiple-value-bind (zt zf ze zs) (funpack z)
      (declare (ignore zs))
      (cond
        ((or (= yt +ft-nan+) (= zt +ft-nan+))
         (deliver-nan yt zt y z))
        ((or (and (= yt +ft-zro+) (= zt +ft-zro+))
             (and (= yt +ft-num+) (= zt +ft-zro+))
             (and (= yt +ft-inf+) (/= zt +ft-nan+)))
         (fp-raise +i-bit+)
         (apply-sign +standard-nan+ ys))
        ((or (and (= yt +ft-zro+) (or (= zt +ft-num+) (= zt +ft-inf+)))
             (and (= yt +ft-num+) (= zt +ft-inf+)))
         (u64 y))
        (t
         (let ((odd 0)
               (thresh (max ze (- ye delta)))
               (xf 0) (xe 0) (xs #\+))
           (tagbody
             (loop while (>= ye thresh)
                   do (when (= yf zf) (go zero-out))
                      (when (< yf zf)
                        (when (= ye ze) (go try-complement))
                        (decf ye)
                        (setf yf (fp-shl yf 1)))
                      (setf yf (u64 (- yf zf)))
                      (when (= ye ze) (setf odd 1))
                      (when (zerop yf) (go zero-out))
                      (loop while (< (fp-hi yf) #x400000)
                            do (decf ye)
                               (setf yf (fp-shl yf 1))))
             (when (>= ye ze)
               (fp-raise +e-bit+)
               (return-from fremstep (fpack yf ye ys +round-off+)))
             (when (< ye (1- ze))
               (return-from fremstep (fpack yf ye ys +round-off+)))
             (setf yf (fp-shr yf 1))
            try-complement
             (setf xf (u64 (- zf yf))
                   xe ze
                   xs (if (char= ys #\-) #\+ #\-))
             (when (or (> xf yf)
                       (and (= xf yf) (zerop odd)))
               (setf xf yf xs ys))
             (loop while (< (fp-hi xf) #x400000)
                   do (decf xe)
                      (setf xf (fp-shl xf 1)))
             (return-from fremstep (fpack xf xe xs +round-off+))
            zero-out
             (return-from fremstep (apply-sign 0 ys)))))))))
